version: '3.8'

services:
  app:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/prac4
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SERVER_PORT=5000
      - GRAYLOG_URL=http://graylog:9000
    ports:
      - "5000:5000"

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=prac4
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data


  adminer:
    image: adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

  zabbix-db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
    volumes:
      - zabbix-postgres-data:/var/lib/postgresql/data

  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    ports:
      - "10051:10051"
    depends_on:
      - zabbix-db
    environment:
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql
    ports:
      - "80:8080"
    depends_on:
      - zabbix-server
      - zabbix-db
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=zabbix-db
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/prac4?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - postgres-exporter

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  graylog:
    image: graylog/graylog:5.2.3
    environment:
      GRAYLOG_ROOT_USERNAME: admin
      GRAYLOG_PASSWORD_SECRET: de5673ec263f99a7ef15c02bc99da340ba1fb62e459039186c62eab75e471edea7add0da892c23a35cc0c899cb7446b7
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_HTTP_BIND_ADDRESS: 0.0.0.0:9000
      GRAYLOG_HTTP_EXTERNAL_URI: http://127.0.0.1:9000/
      GRAYLOG_MONGODB_URI: mongodb://mongo:27017/graylog
    ports:
      - "9000:9000"
      - "12201:12201"
      - "12201:12201/udp"
    depends_on:
      - mongo
      - graylog-datanode
    volumes:
      - graylog-journal:/usr/share/graylog/data/journal
      - graylog-data:/usr/share/graylog/data

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

  graylog-datanode:
    image: graylog/graylog-datanode:5.2.3
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: /var/lib/graylog-datanode/node-id
      GRAYLOG_DATANODE_PASSWORD_SECRET: de5673ec263f99a7ef15c02bc99da340ba1fb62e459039186c62eab75e471edea7add0da892c23a35cc0c899cb7446b7
      GRAYLOG_DATANODE_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_DATANODE_MONGODB_URI: mongodb://mongo:27017/graylog
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8999:8999/tcp"
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    volumes:
      - graylog-datanode:/var/lib/graylog-datanode

volumes:
  postgres-data:
  graylog-journal:
  graylog-data:
  graylog-datanode:
  zabbix-postgres-data:
  mongo-data:
